<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tag extends BaseTag
{

	/**
	 * This utility method removes tags which are not 
	 * associated to websites anymore from database.
	 *
	 */
	public static function removeOrphainTags() {
		$q = new Doctrine_Query();
		$tags = $q
			->select('t.id, COUNT(DISTINCT w.id) as num_websites')
			->from('Tag t')
			->leftJoin('t.Websites w')
			->having('num_websites = 0')
			->groupBy('t.id')
			->execute(array(),Doctrine::HYDRATE_ARRAY);
		if(is_array($tags) && count($tags) > 0) {
			foreach($tags as $tag) {
				Doctrine::getTable('Tag')
					->createQuery()
					->where('id=?',$tag['id'])
					->limit(1)
					->delete()
					->execute();
			}
		}
	}
}