<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannedEmail extends BaseBan
{
	/**
	 * Email ban type.
	 */
	const TYPE = 1;
	
	/**
	 * Sets type on ban entry.
	 *
	 * @param Doctrine_Event $event
	 */
	public function preInsert($event) {
		$this->type = self::TYPE;
	}
	
	/**
	 * IS the email banned ?
	 *
	 * @param string $email
	 * @return boolean
	 */
	public static function isBanned($email) {
		return parent::isBanned(get_class($this),self::TYPE,$email);
	}
	
	/**
	 * Bans an email.
	 *
	 * @param string $email
	 */
	public static function ban($email) {
		parent::ban(get_class($this),self::TYPE,$email);
	}
	
	/**
	 * Removes email from banned ones.
	 *
	 * @param string $email
	 */
	public static function removeBan($email) {
		parent::removeBan(get_class($this),self::TYPE,$email);
	}
}