<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannedHost extends BaseBan
{
	/**
	 * Banned host type.
	 */
	const TYPE = 3;
	
	/**
	 * Sets ban type on insert.
	 *
	 * @param Doctrine_Event $event
	 */
	public function preInsert($event) {
		$this->type = self::TYPE;
		$this->host = str_replace('www.','',$this->host);
	}
	
	/**
	 * Is the Host banned ?
	 *
	 * @param string $url
	 * @return boolean
	 */
	public static function isBanned($host) {
		return parent::isBanned(get_class($this),self::TYPE,$host);
	}
	
	/**
	 * Ban an host.
	 *
	 * @param string $host
	 */
	public static function ban($host) {
		parent::ban(get_class($this),self::TYPE,$host);
	}
	
	/**
	 * Removes Host from banned ones.
	 *
	 * @param string $host
	 */
	public static function removeBan($host) {
		parent::removeBan(get_class($this),self::TYPE,$host);
	}
}